# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{deployer}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael van Rooijen"]
  s.date = %q{2010-01-10}
  s.default_executable = %q{enhancify}
  s.description = %q{longer description of your gem}
  s.email = %q{meskyanichi@gmail.com}
  s.executables = ["enhancify"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/enhancify",
     "deployer.gemspec",
     "lib/deployer.rb",
     "lib/deployer/helpers.rb",
     "lib/deployer/initializer.rb",
     "lib/deployer/tasks/deployer.rake",
     "lib/tasks/apache.rb",
     "lib/tasks/commands.rb",
     "lib/tasks/db.rb",
     "lib/tasks/environment.rb",
     "lib/tasks/gems.rb",
     "lib/tasks/global.rb",
     "lib/tasks/nginx.rb",
     "lib/tasks/passenger.rb",
     "lib/tasks/plugin.rb",
     "lib/tasks/repository.rb",
     "setup/deploy.rb",
     "test/helper.rb",
     "test/test_deployer.rb"
  ]
  s.homepage = %q{http://github.com/meskyanichi/deployer}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{one-line summary of your gem}
  s.test_files = [
    "test/helper.rb",
     "test/test_deployer.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

